name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Instalar dependências
      run: dotnet restore

    - name: Compilar projeto
      run: dotnet build --configuration Release --no-restore

    - name: Testar o projeto
      run: dotnet test --no-restore --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Baixar artefatos do build
      uses: actions/download-artifact@v2

    - name: Login no Azure Container Registry
      run: az acr login --name <SEU_REGISTRO_CONTAINER>

    - name: Build e Push da imagem Docker
      run: |
        docker build -t seu_container_registry/seu_projeto .
        docker push seu_container_registry/seu_projeto

    - name: Deploy no Azure Web App
      run: |
        az webapp create --resource-group seu_resource_group --plan seu_service_plan --name seu_webapp_name --deployment-container-image-name seu_container_registry/seu_projeto
